# Generated by Django 4.1 on 2025-10-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_prescription_is_signed_prescription_signed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='certificate_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='digital_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='certificate_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='digital_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
