# Generated by Django 4.1 on 2025-10-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_prescription_certificate_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='certificate_data',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='digital_signature',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='certificate_data',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='digital_signature',
        ),
        migrations.AddField(
            model_name='prescription',
            name='signed_document',
            field=models.FileField(blank=True, null=True, upload_to='signed_documents/'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='signed_document',
            field=models.FileField(blank=True, null=True, upload_to='signed_documents/'),
        ),
    ]
