# Generated by Django 4.1 on 2025-10-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_prescription_certificate_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='acquirer_document',
            field=models.CharField(blank=True, help_text='Documento de identificação do comprador/adquirente.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='acquirer_name',
            field=models.CharField(blank=True, help_text='Nome completo do comprador/adquirente do medicamento.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_type',
            field=models.CharField(choices=[('COMUM', 'Comum'), ('A1_AMARELA', 'Notificação de Receita A1 (Amarela)'), ('B1_AZUL', 'Notificação de Receita B1 (Azul)'), ('B2_AZUL', 'Notificação de Receita B2 (Azul)'), ('C1_BRANCA', 'Receita de Controle Especial (Branca - Duas Vias)'), ('C2_BRANCA', 'Receita de Controle Especial (Branca - Retinoides)'), ('ANTIMICROBIANO', 'Receita de Antimicrobiano (Branca - Duas Vias)')], default='COMUM', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='sncr_number',
            field=models.CharField(blank=True, help_text='Numeração oficial gerada pelo SNCR para receitas controladas.', max_length=20, null=True, unique=True),
        ),
    ]
