# Generated by Django 4.2.13 on 2025-10-03 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0006_prescription_acquirer_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SncrNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Numeração oficial fornecida pela Vigilância Sanitária.', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('UTILIZADO', 'Utilizado'), ('CANCELADO', 'Cancelado')], default='DISPONIVEL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Médico a quem este número foi designado.', on_delete=django.db.models.deletion.PROTECT, related_name='sncr_numbers', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_sncr_number', to='patients.prescription')),
            ],
        ),
    ]
