# Generated by Django 4.2.13 on 2025-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_sncrnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='sncrnumber',
            name='prescription_type',
            field=models.CharField(choices=[('COMUM', 'Comum'), ('A1_AMARELA', 'Notificação de Receita A1 (Amarela)'), ('B1_AZUL', 'Notificação de Receita B1 (Azul)'), ('B2_AZUL', 'Notificação de Receita B2 (Azul)'), ('C1_BRANCA', 'Receita de Controle Especial (Branca - Duas Vias)'), ('C2_BRANCA', 'Receita de Controle Especial (Branca - Retinoides)'), ('ANTIMICROBIANO', 'Receita de Antimicrobiano (Branca - Duas Vias)')], default='C1_BRANCA', help_text='Tipo de receita a que este número se destina.', max_length=50),
            preserve_default=False,
        ),
    ]
