services:
  backend:
    build: ./backend
    command: /usr/src/app/entrypoint.sh
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=prontuario
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
